[package]
name = "hydro-strike"
version = "0.1.0"
edition = "2021"

default-run = "hydro-strike"

[profile.release]
debug = 1

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
biquad = "0.4.2"
chrono = "0.4.38"
debug-helper = { version = "0.1.0", path = "../../../Rust/debug-helper" }
env_logger = "0.11.5"
ice9-bindings = { version = "0.1.0", path = "ice9-bindings" }
liquid-dsp-bindings-sys = { version = "0.1.0", path = "../../../Rust/liquid-dsp-bindings-sys" }
log = "0.4.22"
log-derive = "0.4.1"
num-complex = "0.4.6"
num-derive = "0.4.2"
num-traits = "0.2.19"
# libhackrf-sys = { version = "0.1.0", path = "../../../../WorkSpace/Rust/libhackrf-sys" }
rustfft = "6.2.0"
signalbool = "0.2.5"
soapysdr = { version = "0.4.0", features = ["log"] }
tokio = { version = "1.40.0", features = ["full"] }
