devices:
- !File
  direction: Rx
    # path: ./tests/test_sample_rx.txt
  path: ./transfered.dat
- !HackRF
  direction: Rx
  freq_mhz: 2427
  serial: 0000000000000000f77c60dc259132c3
- !HackRF
  direction: Tx
  freq_mhz: 2427
  serial: 0000000000000000436c63dc38276e63

